### ISSUE TITLE
Add mana system

### ISSUE THREAD

**Issue by xrtariq2594** [Terasology/MagicalStats#1]
A nice extension to this module would be the introduction of a Mana system. Like many other games, mana will be the main resource pool for (eventually) casting spells. For simplicity's sake, we can assume that mana is equal to the wisdom stat * 10.

For something like this, I would expect to see a ManaComponent, ManaClientSystem, ManaAuthoritySystem, and several mana-based equivalents to the health system events. Specifically these events:
- DoHealEvent
- BeforeHealEvent
- OnHealedEvent
- FullHealthEvent

Optionally, a ManaHUD may be added as well.

**Comment by Cervator** [comment]
Completed by #2 !
