### ISSUE TITLE
Test in multiplayer, especially attack damage, if any

### ISSUE THREAD

**Issue by Cervator** [Terasology/MagicalStats#3]
While reviewing #2 I skipped multiplayer testing for expediency, thinking we could try it out in multiplayer sometime later at an event or so. One thing I noted was that attack events are handled in one spot, with drain damage adding in or even replacing standard damage.

@StripedMonkey might have already tested it and I may just be misunderstanding the code, in which case we can close this. But I wanted to make sure we had a reminder to check on it at some point :-)

**Comment by StripedMonkey** [comment]
MP has not been tested, I had some issues running two sessions of the game
at once probably related to my computer more than the game itself.

**Comment by jdrueckert** [comment]
This module is not part of and not planned to be integrated in the omega line-up.
In the event that it is going to be integrated, the module requires a thorough overhaul anyway, so I'll close this issue until then.
